apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-phi-4
resource:
  instanceType: "Standard_NC24ads_A100_v4"
  labelSelector:
    matchLabels:
      apps: phi-4
inference:
  preset:
    name: phi-4 