apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-service-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: default
  destination:
    namespace: azureserviceoperator-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://raw.githubusercontent.com/Azure/azure-service-operator/main/v2/charts
    chart: azure-service-operator
    targetRevision: 2.15.0
    helm:
      releaseName: aso2
      valuesFrom:
        - configMapRef:
            name: platform-bootstrap-settings
            namespace: argocd
            valuesKey: aso-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
