apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foundry-account
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/tkubica12/d-ai-hybrid-oss-cloud
    targetRevision: main
    path: charts/foundry
  destination:
    server: https://kubernetes.default.svc
    namespace: foundry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
