apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-system
  project: default
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api
    targetRevision: v1.3.0
    path: config/crd/standard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true