apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  destination:
    namespace: envoy-gateway
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/tkubica12/d-ai-hybrid-oss-cloud.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/envoyproxy/gateway.git
      targetRevision: v1.5.1
      path: charts/gateway-helm
      helm:
        releaseName: envoy-gateway
        valueFiles:
          - $values/argocd/values/envoy-gateway.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true