apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  destination:
    namespace: envoy-gateway
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/envoyproxy/gateway
    targetRevision: main
    path: charts/gateway-helm
    helm:
      values: |
        envoyGateway:
          provider:
            type: Kubernetes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true