# Generate platform-runtime.yaml for tenant-access consumption
# This file contains all runtime information needed by tenant-access terraform

resource "local_file" "platform_runtime" {
  filename = var.runtime_output_path
  content = yamlencode({
    # Metadata
    _generated_at = timestamp()
    _warning      = "Auto-generated by platform terraform - DO NOT EDIT MANUALLY"

    # Platform info
    platform = {
      resource_group_name = azurerm_resource_group.main.name
      resource_group_id   = azurerm_resource_group.main.id
      location            = var.location
      subscription_id     = var.subscription_id
    }

    # APIM configuration
    apim = {
      id              = module.ai_platform.apim_id
      name            = module.ai_platform.apim_name
      gateway_url     = module.ai_platform.apim_gateway_url
      openai_api_name = module.ai_platform.openai_api_name
    }

    # AKS configuration
    aks = {
      id   = module.aks_kaito.aks_id
      name = module.aks_kaito.aks_name
    }

    # KAITO models configuration
    kaito = {
      helm_release      = module.kaito.helm_release_name
      service_dns_names = module.kaito.service_dns_names
      models = {
        for name, model in local.enabled_kaito_models :
        name => {
          name           = name
          display_name   = model.displayName
          enabled        = true
          workspace_name = "workspace-${name}"
          endpoint_path  = "/${name}"
          preset         = model.preset
          service_dns    = "kaito-lb-${name}.default.svc.cluster.local"
        }
      }
    }

    # Full catalog for validation (includes disabled models)
    kaito_catalog = {
      for model in local.model_catalog.kaito_models :
      model.name => {
        name    = model.name
        enabled = model.enabled
        preset  = model.preset
      }
    }

    # Foundry configuration
    foundry = {
      account_id   = module.ai_platform.foundry_id
      account_name = module.ai_platform.foundry_name
      endpoint     = module.ai_platform.foundry_endpoint
    }

    # Foundry catalog for validation
    foundry_catalog = {
      for model in local.model_catalog.foundry_models :
      model.name => {
        name    = model.name
        enabled = model.enabled
      }
    }
  })

  depends_on = [
    module.kaito
  ]
}
